### ISSUE TITLE
Update cloud-init implementation

### ISSUE THREAD

**Issue by renevo** [DieterReuter/image-builder-rpi64#31]
Currently cloud-init only uses two of the four possible files:

* user-data
* meta-data
* vendor-data
* network-config

Placeholders should be placed in `/boot` and copied in `chroot-script.sh`

The files should not be placed in `/var/lib/cloud/seed/nocloud-net/` they should be placed in `/var/lib/cloud/seed/nocloud/`. 

`nocloud-net` is a future directory that will be read in 17.1 and specified in the `/boot/cmdline.txt` if you want to remote load ([See documentation for 17.1](http://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html))

This also causes:
```
[local] Exiting. datasource DataSourceNoCloud [seed=/var/lib/cloud/seed/nocloud-net][dsmode=net] not in local mode.
```

There is a bit of confusion about where the `hostname` should be. This should be provided in the meta-data instead of user-data by default. This will require that [flash](https://github.com/hypriot/flash) is updated appropriately as well.

`/meta-data`

```
hostname: myhost
```

`/network-config` 

This is actually where you configure network interfaces (e.g.) The current cloud-init version supports [Network Config v1](http://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html#network-config-v1)

Setting static IP in `/network-config`

```
version: 1
config:
   - type: physical
     name: eth0
     subnets:
        - type: static
          address: 192.168.1.10
          netmask: 255.255.255.0
          gateway: 192.168.1.254
```

`/vendor-data` is basically exactly like user-data, and is usually provided by hosting providers.
